//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `OdometryMelex.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <OdometryMelex.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <Ice/LocalException.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::IceInternal::DefaultUserExceptionFactoryInit<::RoboCompOdometryMelex::HardwareFailedException> iceC_RoboCompOdometryMelex_HardwareFailedException_init("::RoboCompOdometryMelex::HardwareFailedException");

const ::std::string iceC_RoboCompOdometryMelex_OdometryMelex_ids[2] =
{
    "::Ice::Object",
    "::RoboCompOdometryMelex::OdometryMelex"
};
const ::std::string iceC_RoboCompOdometryMelex_OdometryMelex_ops[] =
{
    "getOdometryState",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_RoboCompOdometryMelex_OdometryMelex_getOdometryState_name = "getOdometryState";

}

RoboCompOdometryMelex::HardwareFailedException::~HardwareFailedException()
{
}

const ::std::string&
RoboCompOdometryMelex::HardwareFailedException::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompOdometryMelex::HardwareFailedException";
    return typeId;
}

bool
RoboCompOdometryMelex::OdometryMelex::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompOdometryMelex_OdometryMelex_ids, iceC_RoboCompOdometryMelex_OdometryMelex_ids + 2, s);
}

::std::vector<::std::string>
RoboCompOdometryMelex::OdometryMelex::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompOdometryMelex_OdometryMelex_ids[0], &iceC_RoboCompOdometryMelex_OdometryMelex_ids[2]);
}

::std::string
RoboCompOdometryMelex::OdometryMelex::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompOdometryMelex::OdometryMelex::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompOdometryMelex::OdometryMelex";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompOdometryMelex::OdometryMelex::_iceD_getOdometryState(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    TOdometry ret = this->getOdometryState(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompOdometryMelex::OdometryMelex::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompOdometryMelex_OdometryMelex_ops, iceC_RoboCompOdometryMelex_OdometryMelex_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompOdometryMelex_OdometryMelex_ops)
    {
        case 0:
        {
            return _iceD_getOdometryState(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompOdometryMelex::OdometryMelexPrx::_iceI_getOdometryState(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompOdometryMelex::TOdometry>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompOdometryMelex_OdometryMelex_getOdometryState_name);
    outAsync->invoke(iceC_RoboCompOdometryMelex_OdometryMelex_getOdometryState_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        [](const ::Ice::UserException& ex)
        {
            try
            {
                ex.ice_throw();
            }
            catch(const HardwareFailedException&)
            {
                throw;
            }
            catch(const ::Ice::UserException&)
            {
            }
        });
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompOdometryMelex::OdometryMelexPrx::_newInstance() const
{
    return ::IceInternal::createProxy<OdometryMelexPrx>();
}
/// \endcond

const ::std::string&
RoboCompOdometryMelex::OdometryMelexPrx::ice_staticId()
{
    return OdometryMelex::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompOdometryMelex_OdometryMelex_getOdometryState_name = "getOdometryState";

}

namespace
{

const ::IceInternal::DefaultUserExceptionFactoryInit< ::RoboCompOdometryMelex::HardwareFailedException> iceC_RoboCompOdometryMelex_HardwareFailedException_init("::RoboCompOdometryMelex::HardwareFailedException");

}

RoboCompOdometryMelex::HardwareFailedException::HardwareFailedException(const ::std::string& what) :
    ::Ice::UserException(),
    what(what)
{
}

RoboCompOdometryMelex::HardwareFailedException::~HardwareFailedException() throw()
{
}

::std::string
RoboCompOdometryMelex::HardwareFailedException::ice_id() const
{
    return "::RoboCompOdometryMelex::HardwareFailedException";
}

RoboCompOdometryMelex::HardwareFailedException*
RoboCompOdometryMelex::HardwareFailedException::ice_clone() const
{
    return new HardwareFailedException(*this);
}

void
RoboCompOdometryMelex::HardwareFailedException::ice_throw() const
{
    throw *this;
}

/// \cond STREAM
void
RoboCompOdometryMelex::HardwareFailedException::_writeImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice("::RoboCompOdometryMelex::HardwareFailedException", -1, true);
    ::Ice::StreamWriter< HardwareFailedException, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompOdometryMelex::HardwareFailedException::_readImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< HardwareFailedException, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompOdometryMelex::upCast(OdometryMelex* p) { return p; }

void
::IceProxy::RoboCompOdometryMelex::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< OdometryMelex>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new OdometryMelex;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompOdometryMelex::OdometryMelex::_iceI_begin_getOdometryState(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompOdometryMelex_OdometryMelex_getOdometryState_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompOdometryMelex_OdometryMelex_getOdometryState_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompOdometryMelex_OdometryMelex_getOdometryState_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_RoboCompOdometryMelex_OdometryMelex_getOdometryState_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::RoboCompOdometryMelex::TOdometry
IceProxy::RoboCompOdometryMelex::OdometryMelex::end_getOdometryState(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompOdometryMelex_OdometryMelex_getOdometryState_name);
    ::RoboCompOdometryMelex::TOdometry ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::RoboCompOdometryMelex::HardwareFailedException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompOdometryMelex::OdometryMelex::_newInstance() const
{
    return new OdometryMelex;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompOdometryMelex::OdometryMelex::ice_staticId()
{
    return ::RoboCompOdometryMelex::OdometryMelex::ice_staticId();
}

RoboCompOdometryMelex::OdometryMelex::~OdometryMelex()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompOdometryMelex::upCast(OdometryMelex* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompOdometryMelex_OdometryMelex_ids[2] =
{
    "::Ice::Object",
    "::RoboCompOdometryMelex::OdometryMelex"
};

}

bool
RoboCompOdometryMelex::OdometryMelex::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompOdometryMelex_OdometryMelex_ids, iceC_RoboCompOdometryMelex_OdometryMelex_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompOdometryMelex::OdometryMelex::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompOdometryMelex_OdometryMelex_ids[0], &iceC_RoboCompOdometryMelex_OdometryMelex_ids[2]);
}

const ::std::string&
RoboCompOdometryMelex::OdometryMelex::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompOdometryMelex::OdometryMelex::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompOdometryMelex::OdometryMelex";
    return typeId;
#else
    return iceC_RoboCompOdometryMelex_OdometryMelex_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompOdometryMelex::OdometryMelex::_iceD_getOdometryState(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    TOdometry ret = this->getOdometryState(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompOdometryMelex_OdometryMelex_all[] =
{
    "getOdometryState",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

/// \cond INTERNAL
bool
RoboCompOdometryMelex::OdometryMelex::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompOdometryMelex_OdometryMelex_all, iceC_RoboCompOdometryMelex_OdometryMelex_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompOdometryMelex_OdometryMelex_all)
    {
        case 0:
        {
            return _iceD_getOdometryState(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompOdometryMelex::OdometryMelex::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< OdometryMelex, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompOdometryMelex::OdometryMelex::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< OdometryMelex, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompOdometryMelex::_icePatchObjectPtr(OdometryMelexPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = OdometryMelexPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(OdometryMelex::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
